name: Document

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Go Pages
      run: go install github.com/johnstarich/go/gopages@latest
    - name: 
      run: gopages -gh-pages -gh-pages-token ${{ secrets.GITHUB_TOKEN }}
